### PR TITLE
Feature: add `readonly` attribute support for text field

### PR DESCRIPTION
**Pull request by k0va1**
resolves https://github.com/baoagency/polaris_view_components/issues/302

### CODE REVIEW

**Comment by dan-gamble** [comment]
Would it makes sense for this to be `true` as well when `disabled` is passed based on #302?

**Comment by forsbergplustwo** [comment]
@dan-gamble - My fear with that would be that any code which un-disables a field, would not know it now also has to remove readonly (unless you have a stimulus controller which syncs them in the library). So maybe a good idea to leave readonly to be set explicitly?

**Comment by dan-gamble** [comment]
Makes total sense @forsbergplustwo. Just wasn't sure if this would work differently to "native" Rails if it didn't.

**Comment by forsbergplustwo** [comment]
@dan-gamble - Yeah good question. Guess we want forms to act as natively as possible, so maybe worth doing as you suggested.

**Comment by k0va1** [comment]
Hey @dan-gamble, I didn't get the point why we should set the field to `true` when disabled is also `true`. There are two different attributes specified for different purposes. Here is a definition: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly#attribute_interactions

So I believe that it's reasonable to leave this PR as is

**Comment by kirillplatonov** [comment]
@k0va1 Thanks for the PR!

@dan-gamble In Rails `disabled=true` doesn't add `readonly` attribute automatically. Just double-checked it. So let's keep this PR as is.

**Pull request merged**
