### PR TITLE
v1.5 - Polaris v12 Preview

### PR DESCRIPTION
**Pull request by forsbergplustwo**
# Polaris v12 - Preview
As you all know, this repo is on v11 of Polaris, and Shopify is on v12. I feel like it's going to be a while (and perhaps a tough upgrade) to get this repo to Polaris v12. Also, Shopify is moving more to WebComponents in general and I think it's worth waiting to see what they come up with before putting in the effort here.

So what do we do? Luckily, I think there's a simple answer in this PR.

## What this PR does:

Applies the beta version of Polaris v12 design styles, which Shopify already rolled out in the v11 if `@shopify/polaris` css package.. although in a late beta state.

1. Bumps `@shopify/polaris` to the latest v11 release (v11.26).
2. Adds `Polaris-Summer-Editions-2023` class to `<html>` tag, which applies all the styling to existing markup of the lookbook previews.

### Before: v11 Empty State component
CleanShot 2024-01-18 at 16 44 17

### After: v12-preview Empty State component:
CleanShot 2024-01-18 at 16 44 38

## How to use in your app (once merged)
1. Add `Polaris-Summer-Editions-2023` class to your applications `<html>` tag.

## What do you all think of this?
I checked over the components in the lookbook and I'd say this is 98% complete. There are a couple minor issues with secondary action dropdowns, button groups (pagination).. but nothing huge. We could perhaps setup a simple CSS file with a few overrides to correct these minor things until we know a more long-term direction.

Let me know your thoughts 🤓

### CODE REVIEW

**Comment by forsbergplustwo** [comment]
Note: You can also try this branch in your own apps now, by adjusting your `Gemfile`:

```Gemfile
gem "polaris_view_components", "~> 1.4", github: "forsbergplustwo/polaris_view_components", branch: "v12-preview"
```

And adding the html class mentioned earlier.

**Comment by stuartchaney** [comment]
I love the interim workaround here @forsbergplustwo 👏

**Comment by kirillplatonov** [comment]
It looks like a great and pragmatic alternative to full blown v12 upgrade. 👏 Styles look exactly the same. I tested and compared lookbooks and here’s the list of issues I found:
- Autocomplete checkboxes + MultiChoice OptionList
- Banners
- Card paddings too small
- Filters dropdown overlapped by table content
- Modal paddings too big
- Missing styles for selected item in NavigationList
- Page action group styles are broken
- Popover content and actions margins
- Tooltips overlapped by card on long pages
- Pagination styles are a bit different

After fixing them we could release v1.5 and make new UI optional via `Polaris-Summer-Editions-2023` class. Once Shopify will make further progress with Polaris we could fully migrate in v2.0 with breaking changes.

**Comment by forsbergplustwo** [comment]
@kirillplatonov - Fantastic, I'll be happy to help on this too. I don't have access to setup Milestones in the repo or "todos". Would the correct way to track this be create issues with a `v1.5` label?

**Pull request merged**
