### PR TITLE
Banners

### LINKED ISSUE #354: Banners
Background: https://github.com/baoagency/polaris_view_components/pull/352

### PR DESCRIPTION
**Pull request by forsbergplustwo**
Closes #354 

TODO

- [x] Padding
- [x] withinPage
- [x] withinContainer
- [x] Button styles
- [x] Secondary action styles
- [x] Layout change to move icon + title to top row with bg color

### CODE REVIEW

**Comment by kirillplatonov** [comment]
@forsbergplustwo maybe it will make sense to have configuration setting on the back-end to turn on v12 styling? We could use it to tweak markup for v12 version a little bit. It seems like moving the icon from the left column to the top will be a biggest change required for banners.

**Comment by forsbergplustwo** [comment]
@kirillplatonov - I'll give it a shot, but I think we have to be careful of going too far with these customizations 😅

**Comment by forsbergplustwo** [comment]
Regarding a setting, would they not just be able to pin the gem to an earlier version if they really don't want the upgrade?

**Comment by kirillplatonov** [comment]
@forsbergplustwo If we're going to make new styles optional then we'll need to keep markup compatible with both v11 and v12 css. It's an extra work without real benefits. Thinking more about this it might be easier to just go with v2.0 release that will include only v12 styles. This way we could adjust markup without additional configuration. The only requirement would be to introduce new helper `polaris_html_classes` similar to existing `polaris_html_styles`. This helper could be used to add `Polaris-Summer-Editions-2023` class to `html` tag automatically. What do you think?

**Comment by forsbergplustwo** [comment]
@kirillplatonov - Sounds great! I think dropping backwards compatability will allow us to get the final parts really nice. It is a bit more complicated to adjust the markup too, but I think it's not too many components that need it.

**Comment by forsbergplustwo** [comment]
@kirillplatonov - Do you want to review these before I merge to the 'polaris-v12' branch?

This turned out pretty good in the end, and match up nicely:

CleanShot 2024-02-09 at 18 30 46@2x

CleanShot 2024-02-09 at 18 31 07@2x

CleanShot 2024-02-09 at 18 34 56@2x
(Our withinContainer has slightly more padding than Shopify's, but it's a pain to change)

**Pull request merged**
