### PR TITLE
Upgrade to Polaris 10: Components

### PR DESCRIPTION
**Pull request by kirillplatonov**
Other related PR's: #297, #298

### Todo

- [x] Update CSS
- [x] Update icons
- [x] Update tokens
- [x] Check all components
- [x] Add `polaris_html_styles` to installer
- [x] Check if we still need `polaris_inversed_colors`
- [x] Update README & screenshot
- [x] Restore four sections layout

#### Actions
- [x] Button
- [x] ButtonGroup
- [x] PageActions
- [x] SettingToggle

#### Layout and structure
- [x] Card
- [x] CalloutCard
- [x] EmptySearchResults
- [x] EmptyState
- [x] FormLayout
- [x] Layout
- [x] Stack
- [x] Page
- [x] TextContainer

#### Selection and input
- [x] Autocomplete
- [x] Checkbox
- [x] ChoiceList
- [x] ContextualSaveBar
- [x] Dropzone
- [x] Filters
- [x] InlineError
- [x] RadioButton
- [x] Select
- [x] Tag
- [x] TextField

#### Images and icons
- [x] Avatar
- [x] Icon
- [x] KeyboardKey
- [x] Thumbnail

#### Feedback indicators
- [x] Badge
- [x] Banner
- [x] ExceptionList
- [x] ProgressBar
- [x] SkeletonBodyText
- [x] SkeletonDisplayText
- [x] SkeletonPage
- [x] SkeletonThumbnail
- [x] Spinner
- [x] Toast

#### Typography
- [x] Caption
- [x] DisplayText
- [x] Heading
- [x] Subheading
- [x] TextStyle
- [x] VisuallyHidden

#### Tables
- [x] DataTable
- [x] IndexTable

#### Lists
- [x] ActionList
- [x] DescriptionList
- [x] List
- [x] OptionList
- [x] ResourceItem
- [x] ResourceList

#### Navigation
- [x] FooterHelp
- [x] Link
- [x] Navigation
- [x] Pagination
- [x] Tabs

#### Overlays
- [x] Modal
- [x] Popover

#### Utilities
- [x] Collapsible
- [x] FormBuilder
- [x] Frame
- [x] Scrollable
- [x] ShopifyNavigation
- [x] Spacer
- [x] UrlHelpers

### New components
- [x] Box
- [x] AlphaStack -> VerticalStack/HorizontalStack
- [x] Inline
- [x] Text
- [x] InlineCode
- [x] Divider
- [x] Bleed
- [x] HorizontalGrid

### CODE REVIEW

**Comment by kirillplatonov** [comment]
@dan-gamble wanted to discuss how we should handle Polaris changes in Card/Stack components. Shopify introduced 3 versions of these components in Polaris 10: Card, AlphaCard, and LegacyCard. I'm hesitant to bring this complexity into ViewComponents and want to keep only Card and under the hood use markup for LegacyCard. Once Shopify will kill LegacyCard completely we could make a release with breaking changes or try to reimplement the old Card features using new primitives (at least partially). What do you think?

**Comment by kirillplatonov** [comment]
Not sure if anyone will want to use `Alpha` versions of components considering it's WIP and even Shopify uses `Legacy` components everywhere in Polaris codebase. Maybe let's wait at least for the `Beta` stage before adding new components to the gem? Will be less work for us and the components markup on the `Beta` stage should be more stable.

**Comment by dan-gamble** [comment]
@kirillplatonov RE: The navigation component, do you think it makes sense to try and incorporate the app bridge way of doing it so we can utilise the admin sidebar?

**Comment by kirillplatonov** [comment]
We should probably deprecate the old ShopifyNavigation component. As for integration with AppBridge - I think it should be in the separate library/gem as it's used only by embedded apps and is not related to Polaris. We still have Navigation component though but it's used by standalone apps: https://polarisviewcomponents.org/lookbook/inspect/navigation/basic

**Pull request merged**
